name: Smoke test "base-alpine" build

on: 
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    paths:
      - src/base-alpine/**
      - .github/workflows/smoke-base-alpine.yaml
      - .github/actions/**
      - build/**
jobs:
  smoke-test:
    name: Smoke test
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Disable AppArmor
      run: |
       set -e
       echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns      

    - name: Smoke test
      id: smoke_test
      uses: ./.github/actions/smoke-test
      with:
        image: base-alpine
